name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, jruby, truffleruby]
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update -qq && sudo apt install libsdl2-dev
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
